worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: info

is-testing: false

server-port: 8082
server-grpc-port: 8081

secdist-path: /secure_data.json

dbconnection: 'postgresql://authorization_user:password@localhost:5432/authorization_db_1'

client-user-service-endpoint: 'localhost:8081'
client-user-service-deadline: '2s'
access-token-ttl: '1h'