openapi: 3.0.0
info:
    title: Authorization
    version: 1.0.0
    description: Сервис для авторизации пользователей


components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        Empty:
            additionalProperties: false
            type: object
            properties: {}
        Error:
            additionalProperties: false
            type: object
            properties: {}
        CreateUser:
                type: object
                additionalProperties: false
                properties:
                    phoneNumber:
                            type: string
                            maxLength: 18
                    fullName:
                            type: string
                            maxLength: 128
                    birthDate:
                            type: string
                            format: date
                            maxLength: 10
                    gender:
                            type: string
                            pattern: (male|female)
                            minLength: 4
                            maxLength: 5
                required:
                - phoneNumber
                - fullName
                - birthDate
                - gender
        